using IdentityService.Application.DTOs;
using IdentityService.Application.Interfaces;
using IdentityService.Domain.Entities;
using IdentityService.Domain.Interfaces;
using System.Security.Cryptography;

namespace IdentityService.Application.Services;

public class AuthService : IAuthService
{
    private readonly IAuthRepository _repository;
    private readonly IEmailService _emailService;

    public AuthService(IAuthRepository repository, IEmailService emailService)
    {
        _repository = repository;
        _emailService = emailService;
    }

    public async Task<AuthResponseDto> RegisterAsync(RegisterDto dto)
    {
        var exists = await _repository.EmailExistsAsync(dto.Email.ToLower());
        if (exists)
            throw new InvalidOperationException("Email already registered.");

        var user = new User
        {
            FullName = dto.FullName.Trim(),
            Email = dto.Email.ToLower().Trim(),
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(dto.Password),
            Role = "CUSTOMER"
        };

        user = await _repository.CreateUserAsync(user);

        return new AuthResponseDto
        {
            Token = string.Empty, // Token will be generated by controller
            FullName = user.FullName,
            Email = user.Email,
            Role = user.Role,
            ExpiresAt = DateTime.UtcNow.AddHours(8)
        };
    }

    public async Task<OtpSendResultDto> SendRegistrationOtpAsync(SendOtpRequestDto dto)
    {
        var normalizedEmail = dto.Email.ToLower().Trim();
        var exists = await _repository.EmailExistsAsync(normalizedEmail);
        if (exists)
        {
            throw new InvalidOperationException("Email already registered.");
        }

        var otpCode = RandomNumberGenerator.GetInt32(100000, 1000000).ToString();
        await _repository.UpsertOtpAsync(normalizedEmail, otpCode, DateTime.UtcNow.AddMinutes(15));

        await _emailService.SendOtpEmailAsync(normalizedEmail, dto.FullName.Trim(), otpCode);
        return new OtpSendResultDto { Message = "OTP sent to your email." };
    }

    public async Task<AuthResponseDto> VerifyRegistrationOtpAsync(VerifyRegistrationRequestDto dto)
    {
        var normalizedEmail = dto.Email.ToLower().Trim();
        var exists = await _repository.EmailExistsAsync(normalizedEmail);
        if (exists)
        {
            throw new InvalidOperationException("Email already registered.");
        }

        var otp = await _repository.GetLatestOtpAsync(normalizedEmail);
        if (otp is null || otp.IsUsed)
        {
            throw new UnauthorizedAccessException("No active OTP found. Please request a new OTP.");
        }

        if (otp.ExpiresAt < DateTime.UtcNow)
        {
            throw new UnauthorizedAccessException("OTP has expired. Please request a new OTP.");
        }

        if (!string.Equals(otp.OtpCode, dto.OtpCode.Trim(), StringComparison.Ordinal))
        {
            throw new UnauthorizedAccessException("Invalid OTP code.");
        }

        var user = new User
        {
            FullName = dto.FullName.Trim(),
            Email = normalizedEmail,
            PasswordHash = BCrypt.Net.BCrypt.HashPassword(dto.Password),
            Role = "CUSTOMER"
        };

        user = await _repository.CreateUserAsync(user);
        await _repository.MarkOtpAsUsedAsync(otp.Id);

        return new AuthResponseDto
        {
            Token = string.Empty,
            FullName = user.FullName,
            Email = user.Email,
            Role = user.Role,
            ExpiresAt = DateTime.UtcNow.AddHours(8)
        };
    }

    public async Task<AuthResponseDto> LoginAsync(LoginDto dto)
    {
        var user = await _repository.GetByEmailAsync(dto.Email.ToLower());

        if (user is null || !BCrypt.Net.BCrypt.Verify(dto.Password, user.PasswordHash))
            throw new UnauthorizedAccessException("Invalid email or password.");

        if (!user.IsActive)
            throw new UnauthorizedAccessException("Account is deactivated.");

        return new AuthResponseDto
        {
            Token = string.Empty, // Token will be generated by controller
            FullName = user.FullName,
            Email = user.Email,
            Role = user.Role,
            ExpiresAt = DateTime.UtcNow.AddHours(8)
        };
    }

    public async Task<UserProfileDto?> GetProfileAsync(int userId)
    {
        var user = await _repository.GetByIdAsync(userId);
        if (user is null) return null;

        return new UserProfileDto
        {
            Id = user.Id,
            FullName = user.FullName,
            Email = user.Email,
            Role = user.Role,
            IsActive = user.IsActive,
            CreatedAt = user.CreatedAt
        };
    }

    public async Task<List<UserProfileDto>> GetAllUsersAsync()
    {
        var users = await _repository.GetAllUsersAsync();

        return users.Select(user => new UserProfileDto
        {
            Id = user.Id,
            FullName = user.FullName,
            Email = user.Email,
            Role = user.Role,
            IsActive = user.IsActive,
            CreatedAt = user.CreatedAt
        }).ToList();
    }

    public Task<int> GetUsersCountAsync()
    {
        return _repository.GetUsersCountAsync();
    }

    public Task<bool> UpdateUserStatusAsync(int userId, bool isActive)
    {
        return _repository.UpdateUserStatusAsync(userId, isActive);
    }
}
